package com.trsvax.tapestry.facebook.opengraph;

public enum ContentType {
	ACTIVITY,SPORT,BAR,COMPANY,CAFE,HOTEL,RESTAURANT,CAUSE,SPORTS_LEAGUE,SPORTS_TEAM,BAND,GOVERNMENT,NON_PROFIT,SCHOOL,UNIVERSITY,ACTOR,ATHLETE,AUTHOR,DIRECTOR,MUSICIAN,POLITICIAN,PUBLIC_FIGURE,CITY,COUNTRY,LANDMARK,STATE_PROVINCE,ALBUM,BOOK,DRINK,FOOD,GAME,PRODUCT,SONG,MOVIE,TV_SHOW,BLOG,WEBSITE,ARTICLE;


	public String toString() {
		return name().toString().toLowerCase();
	}

}
